# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Developer's Journal"

# A description of your site for meta tag, search engine results.
description: "A small journal about development topics I stumbled upon"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://hadesrofl.github.io/"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Tags
    url: /tags

# The shortname for your Disqus site to enable comments.
# disqus: justgoodthemes

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; Developer's Journal all rights reserved. Theme by [JustGoodThemes](https://www.justgoodthemes.com). Journal icon created by [Freepik - Flaticon](https://www.flaticon.com/free-icons/journal)"
  has_social: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-mermaid

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:year/:month/:day/:title

# Conversion
markdown: kramdown

mermaid:
  src: /assets/js/mermaid.min.js

# Sass
sass:
  sass_dir: _sass
  style: compressed
